import InfoPageLayout from '../../components/InfoPageLayout';

const sections = [
  { title: '1. Acceptance of Terms', content: 'By accessing or using AdaptLearn\'s platform, you agree to be bound by these Terms of Service. If you are using AdaptLearn on behalf of an organization, you represent that you have authority to bind that organization to these terms.' },
  { title: '2. Service Description', content: 'AdaptLearn provides an AI-powered employee onboarding and skill development platform. Our services include: resume-based skill analysis, personalized learning roadmap generation, module libraries with curated resources, interactive quizzes, skill gap reporting, and HR employee management tools.' },
  { title: '3. User Accounts', content: 'You are responsible for maintaining the confidentiality of your account credentials. HR administrators can create employee accounts with auto-generated passwords. Users must not share account credentials or allow unauthorized access. We reserve the right to suspend accounts that violate these terms.' },
  { title: '4. Acceptable Use', content: 'You agree to use AdaptLearn only for legitimate professional development and onboarding purposes. You may not: (a) upload false or misleading resumes, (b) attempt to reverse-engineer our AI algorithms, (c) use the platform for unauthorized data scraping, or (d) violate any applicable laws or regulations.' },
  { title: '5. Intellectual Property', content: 'AdaptLearn owns all rights to the platform, including UI designs, algorithms, learning path generation logic, and analytics features. Content generated by the Gemini API is subject to Google\'s terms. Your uploaded documents and quiz responses remain your property.' },
  { title: '6. AI-Generated Content', content: 'Learning roadmaps, module recommendations, and skill analyses are generated by AI and provided as-is. While we strive for accuracy, AI-generated content should be used as guidance rather than definitive assessments. Organizations should complement AI recommendations with human judgment.' },
  { title: '7. Limitation of Liability', content: 'AdaptLearn is provided "as is" without warranties of any kind. We are not liable for: (a) decisions made based on AI-generated skill analyses, (b) third-party content linked in module libraries, (c) data loss due to browser storage limitations, or (d) service interruptions beyond our reasonable control.' },
  { title: '8. Modifications', content: 'We may update these terms at any time. Continued use of AdaptLearn after changes constitutes acceptance of the updated terms. Significant changes will be communicated via email to registered users.' },
];

export default function TermsOfServicePage() {
  return (
    <InfoPageLayout title="Terms of Service" subtitle="Please read these terms carefully before using the AdaptLearn platform.">
      <div className="space-y-1">
        <p className="text-xs text-ink-muted mb-6">Last updated: March 21, 2026</p>
        {sections.map((s, i) => (
          <div key={i} className="glass-effect rounded-2xl p-6 bg-white/50 border border-white/60 shadow-sm mb-4">
            <h3 className="font-semibold text-ink text-base mb-2">{s.title}</h3>
            <p className="text-ink-secondary text-sm leading-relaxed">{s.content}</p>
          </div>
        ))}
      </div>
    </InfoPageLayout>
  );
}
